### ISSUE TITLE
RPC v0.6 tracking issue

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1481]
~The full v0.6 specification has not yet been released, but the bulk of the intended changes are in [this PR](https://github.com/starkware-libs/starknet-specs/pull/149/files). Once the release is out we should properly analyze the full diff.~

The [first release candidate](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0-rc0) is available.

Differences from the diff itself:

- [x] transaction version is now an enum per txn variant(for broadcasted transactions included)
- [ ] `BLOCK_NOT_FOUND` message changed to `"Block not found"`
- [x] #1563
- [x] ~~`state_diff`, `fee_transfer_invocation` and `validate_invocation` are again required for traces (this is likely a bug, wait for spec fix before implementing this)~~ Fixed in the specification.
- [x] #1554
- [x] #1542

Additional changes:
- Follow-up post-rc2 changes: https://github.com/starkware-libs/starknet-specs/pull/174:
  - [x] #1580 
  - [x] #1581 
  - [x] #1582

**Comment by kkovaacs** [comment]
The OpenRPC diffs from 0.5.1 to 0.6.0-rc0:
[0.5.1-to-0.6.0-rc0-diffs.zip](https://github.com/eqlabs/pathfinder/files/13309497/0.5.1-to-0.6.0-rc0-diffs.zip)

**Comment by kkovaacs** [comment]
There was a discussion regarding v3 transaction representation in older JSON-RPC versions with the following suggestions:

- We should not raise an error if a v3 transaction would appear in the results of a request.
- Instead, we should map v3 transactions into "v2" transactions as follows:
  - The `version` field cannot be 3 for these transactions because JSON-RPC 0.4/0.5 does not have that as a valid version. We should just lie about the version number.
  - `nonce_data_availability_mode`, `fee_data_availability_mode`, `tip`, `paymaster_data` and `account_deployment_data` cannot be represented and should just be omitted.
  - `max_fee` should be set to `resource_bounds.l1_gas.max_amount * resource_bounds.l1_gas.max_price_per_unit`.
