### ISSUE TITLE
Transaction & Receipt tracking sync

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1996]
Implement tracking sync for transactions and receipts.

- [ ] Create a source similar to [`EventSource`](https://github.com/eqlabs/pathfinder/blob/main/crates/pathfinder/src/sync/track.rs#L150-L153).
- [ ] Processing stage to verify hashes
- [ ] Connect the plumbing
