### ISSUE TITLE
p2p roadmap

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#247]
Tracking issue for rough p2p roadmap.

We have decided on using libp2p where possible. However, there are still quite a few design choices that need to made and motivated.

- [x] peer discovery mechanism
- [ ] data exchange protocol (probably a simple request / response type, [filecoin example](https://spec.filecoin.io/algorithms/block_sync/))
- [ ] serialisation format
- [ ] compression format
- [ ] sync process (possibly snapshots only initially?)
- [ ] tracking head of chain (likely using gossipsub)

## Additional work
We will need to refactor storage to allow for disjoint (non-sequential) inputs. This will allow for getting blocks out of order, as well as only getting partial block information e.g. missing contract definitions or state diffs.

This sync process will also need to change to handle this.

**Comment by CHr15F0x** [comment]
This is by no means a complete [comparison](https://hackmd.io/Thb_MxTURyqMVDxmDn1RYQ).

**Comment by CHr15F0x** [comment]
Compression: it's worth checking if there are alternatives to snappy that possess the same [property](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#why-are-we-using-snappy-for-compression).

**Comment by Mirko-von-Leipzig** [comment]
There is now a shared forum for designing this.
